export const BLOG_POSTS = [
  {
    image: 'https://picsum.photos/id/1015/600/400',
    tag: 'INTERVIEW',
    date: 'September 09, 2022',
    title: '100 JavaScript interview questions and answers',
    slug: '100-javascript-interview-questions-and-answers',
  },
  {
    image: 'https://picsum.photos/id/1016/600/400',
    tag: 'INTERVIEW',
    date: 'September 09, 2023',
    title: '30 Days JavaScript',
    slug: '30-days-javascript',
  },
  {
    image: 'https://picsum.photos/id/1018/600/400',
    tag: 'TUTORIAL',
    date: 'March 10, 2024',
    title: 'Angular Signals Deep Dive',
    slug: 'angular-signals-deep-dive',
  },
  {
    image: 'https://picsum.photos/id/1020/600/400',
    tag: 'GUIDE',
    date: 'May 01, 2023',
    title: 'RxJS Operators Explained',
    slug: 'rxjs-operators-explained',
  },
  {
    image: 'https://picsum.photos/id/1024/600/400',
    tag: 'TIPS',
    date: 'April 15, 2023',
    title: '10 VS Code Tricks for Angular Developers',
    slug: '10-vs-code-tricks-for-angular-developers',
  },
  {
    image: 'https://picsum.photos/id/1025/600/400',
    tag: 'API',
    date: 'January 22, 2023',
    title: 'REST vs GraphQL in Angular',
    slug: 'rest-vs-graphql-in-angular',
  },
  {
    image: 'https://picsum.photos/id/1027/600/400',
    tag: 'CLEAN CODE',
    date: 'June 30, 2023',
    title: 'How to Write Maintainable Angular Code',
    slug: 'how-to-write-maintainable-angular-code',
  },
  {
    image: 'https://picsum.photos/id/1033/600/400',
    tag: 'INTERVIEW',
    date: 'July 12, 2023',
    title: 'Top Data Structures for Frontend Devs',
    slug: 'top-data-structures-for-frontend-devs',
  },
  {
    image: 'https://picsum.photos/id/1035/600/400',
    tag: 'DESIGN',
    date: 'October 19, 2022',
    title: 'Mastering Tailwind CSS in Angular',
    slug: 'mastering-tailwind-css-in-angular',
  },
  {
    image: 'https://picsum.photos/id/1040/600/400',
    tag: 'DEVOPS',
    date: 'November 11, 2022',
    title: 'Deploy Angular Apps with Docker',
    slug: 'deploy-angular-apps-with-docker',
  },
  {
    image: 'https://picsum.photos/id/1043/600/400',
    tag: 'TYPESCRIPT',
    date: 'August 09, 2022',
    title: 'Advanced TypeScript Tips',
    slug: 'advanced-typescript-tips',
  },
  {
    image: 'https://picsum.photos/id/1044/600/400',
    tag: 'MOBILE',
    date: 'February 28, 2023',
    title: 'Building PWA with Angular',
    slug: 'building-pwa-with-angular',
  },
  {
    image: 'https://picsum.photos/id/1045/600/400',
    tag: 'BEST PRACTICES',
    date: 'March 05, 2023',
    title: 'Code Standards for Angular Projects',
    slug: 'code-standards-for-angular-projects',
  },
  {
    image: 'https://picsum.photos/id/1050/600/400',
    tag: 'PERFORMANCE',
    date: 'April 01, 2024',
    title: 'Speed Up Angular Apps',
    slug: 'speed-up-angular-apps',
  },
  {
    image: 'https://picsum.photos/id/1051/600/400',
    tag: 'TESTING',
    date: 'January 10, 2024',
    title: 'Unit Testing Angular Components',
    slug: 'unit-testing-angular-components',
  },
  {
    image: 'https://picsum.photos/id/1052/600/400',
    tag: 'HOOKS',
    date: 'December 20, 2023',
    title: 'Understanding Angular Lifecycle Hooks',
    slug: 'understanding-angular-lifecycle-hooks',
  },
  {
    image: 'https://picsum.photos/id/1053/600/400',
    tag: 'ROUTING',
    date: 'May 01, 2024',
    title: 'Angular Router - Complete Guide',
    slug: 'angular-router-complete-guide',
  },
  {
    image: 'https://picsum.photos/id/1055/600/400',
    tag: 'SIGNALS',
    date: 'April 10, 2024',
    title: 'Signals vs Observables in Angular 17',
    slug: 'signals-vs-observables-in-angular-17',
  },
  {
    image: 'https://picsum.photos/id/1057/600/400',
    tag: 'COMPARISON',
    date: 'June 01, 2023',
    title: 'Angular vs React: 2024 Edition',
    slug: 'angular-vs-react-2024-edition',
  },
  {
    image: 'https://picsum.photos/id/1060/600/400',
    tag: 'LIBRARIES',
    date: 'July 15, 2023',
    title: 'Top 10 Angular Libraries in 2024',
    slug: 'top-10-angular-libraries-in-2024',
  },
];
